---
- name: Setup Ubuntu VM for Semaphore + Filebeat
  hosts: ubuntu_vms
  become: true
  gather_facts: true

  vars:
    python_scripts_src: ./python-scripts
    python_scripts_dest: /home/ubuntu/python-scripts
    log_dirs:
      - /var/log/vm_state
      - /var/log/bot_data
      - /var/log/ansible
      - /var/log/opentofu
    ubuntu_packages:
      - python3
      - python3-pip
      - python3-venv
      - curl
      - wget
      - git
      - htop
      - vim
      - unzip
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - lsb-release
      - sudo
      - openssh-server
    
    python_packages:
      - psutil
      - requests
      - selenium
      - schedule

  tasks:
    - name: Update apt package cache
      apt:
        update_cache: true
        cache_valid_time: 3600
      tags: ['system']
    
    - name: Install system packages
      apt:
        name: "{{ ubuntu_packages }}"
        state: present
      tags: ['system']

    - name: Ensure SSH service is running
      service:
        name: ssh
        state: started
        enabled: true
      tags: ['ssh']

    - name: Create Python virtual environment
      command:
        cmd: python3 -m venv /opt/monitoring/venv
        creates: /opt/monitoring/venv/bin/activate
      become: true
      tags: ['python']

    - name: Install Python packages
      pip:
        name: "{{ python_packages }}"
        state: present
        executable: pip3
      tags: ['python']

    - name: Ensure log directories exist
      file:
        path: "{{ item }}"
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      loop: "{{ log_dirs }}"
      tags: logs
    

    - name: Copy Python scripts
      copy:
        src: "{{ python_scripts_src }}/"
        dest: "{{ python_scripts_dest }}/"
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      tags: scripts

    - name: Configure timezone
      timezone:
        name: "{{ ansible_timezone | default('UTC') }}"
      tags: ['system']
      
    - name: Enable and start systemd-timesyncd (GCP compatible)
      systemd:
        name: systemd-timesyncd
        enabled: true
        state: started
      tags: ['system']

    - name: Download and install Filebeat
      apt:
        deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.15.0-amd64.deb
        state: present
      tags: filebeat

    - name: Copy Filebeat configuration
      copy:
        src: ./filebeat.yml
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'
      tags: filebeat

    - name: Enable and start Filebeat service
      systemd:
        name: filebeat
        enabled: true
        state: started
      tags: filebeat

    - name: Display system information
      debug:
        msg: |
          Ubuntu system setup completed successfully!
          OS: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Architecture: {{ ansible_architecture }}
          Python version: {{ ansible_python_version }}
          Hostname: {{ ansible_hostname }}
          IP Address: {{ ansible_default_ipv4.address }}
      tags: ['info']

  handlers:
    - name: reload systemd
      systemd:
        daemon_reload: true